# Generated by Django 4.2.30 on 2026-06-12 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URLスラッグ')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('title', models.CharField(max_length=120, verbose_name='タイトル')),
                ('concept', models.CharField(max_length=80, verbose_name='学習概念')),
                ('summary', models.TextField(verbose_name='概要')),
                ('goal', models.TextField(verbose_name='学習目標')),
                ('explanation', models.TextField(verbose_name='解説')),
                ('practice_task', models.TextField(verbose_name='練習内容')),
                ('hint', models.TextField(blank=True, verbose_name='ヒント')),
                ('starter_code', models.TextField(blank=True, verbose_name='初期コード')),
                ('sample_solution', models.TextField(verbose_name='正解コード')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '練習コンテンツ',
                'verbose_name_plural': '練習コンテンツ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField(verbose_name='提出コード')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解')),
                ('feedback', models.CharField(max_length=255, verbose_name='フィードバック')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提出日時')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='practice.practicecontent', verbose_name='練習コンテンツ')),
            ],
            options={
                'verbose_name': '提出履歴',
                'verbose_name_plural': '提出履歴',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('last_submitted_code', models.TextField(blank=True, verbose_name='最後に提出したコード')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='practice.practicecontent', verbose_name='練習コンテンツ')),
            ],
            options={
                'verbose_name': '学習進捗',
                'verbose_name_plural': '学習進捗',
            },
        ),
    ]
