# Generated by Django 4.2.30 on 2026-06-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicecontent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='practiceprogress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='practicesubmission',
            options={},
        ),
        migrations.AlterModelTable(
            name='practicecontent',
            table='content',
        ),
        migrations.AlterModelTable(
            name='practiceprogress',
            table='progress',
        ),
        migrations.AlterModelTable(
            name='practicesubmission',
            table='submission',
        ),
    ]
