# Generated by Django 4.2.30 on 2026-06-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_remove_practicesubmission_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesubmission',
            name='feedback',
        ),
    ]
